steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/forex-ai:${SHORT_SHA}', '.']
  
  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/forex-ai:${SHORT_SHA}']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'forex-ai'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/forex-ai:${SHORT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8000'
      - '--cpu'
      - '1'
      - '--memory'
      - '2Gi'
      - '--timeout'
      - '300'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'ENVIRONMENT=production,DEBUG=false,LOG_LEVEL=INFO,WEB_PORT=8000,ENABLE_DOCS=true,ENABLE_PERFORMANCE_LOGGING=true,POSTGRES_USER=${_POSTGRES_USER},POSTGRES_DB=${_POSTGRES_DB},POSTGRES_HOST=${_POSTGRES_HOST},POSTGRES_PORT=${_POSTGRES_PORT},REDIS_HOST=${_REDIS_HOST},REDIS_PORT=${_REDIS_PORT},GOOGLE_API_KEY=${_GOOGLE_API_KEY},GCP_LOCATION=${_GCP_LOCATION},GCP_PROJECT_ID=${PROJECT_ID},REASONING_MODEL=${_REASONING_MODEL},CHAT_MODEL=${_CHAT_MODEL},VISION_MODEL=${_VISION_MODEL},EMBEDDING_MODEL=${_EMBEDDING_MODEL},SUPABASE_URL=${_SUPABASE_URL}'
      - '--set-secrets'
      - 'POSTGRES_PASSWORD=projects/${PROJECT_NUMBER}/secrets/POSTGRES_PASSWORD:latest,REDIS_PASSWORD=projects/${PROJECT_NUMBER}/secrets/REDIS_PASSWORD:latest,ALPHA_VANTAGE_API_KEY=projects/${PROJECT_NUMBER}/secrets/ALPHA_VANTAGE_API_KEY:latest,THE_NEWS_API_KEY=projects/${PROJECT_NUMBER}/secrets/THE_NEWS_API_KEY:latest,YOUTUBE_API_KEY=projects/${PROJECT_NUMBER}/secrets/YOUTUBE_API_KEY:latest,JWT_SECRET_KEY=projects/${PROJECT_NUMBER}/secrets/JWT_SECRET_KEY:latest,SUPABASE_KEY=projects/${PROJECT_NUMBER}/secrets/SUPABASE_KEY:latest,SUPABASE_SERVICE_KEY=projects/${PROJECT_NUMBER}/secrets/SUPABASE_SERVICE_KEY:latest,SECRET_KEY=projects/${PROJECT_NUMBER}/secrets/SECRET_KEY:latest'

substitutions:
  _REGION: us-central1
  _REPOSITORY: forex-ai-repo
  _POSTGRES_USER: forex_user
  _POSTGRES_DB: forex_db
  _POSTGRES_HOST: localhost
  _POSTGRES_PORT: "5432"
  _REDIS_HOST: redis-12651.c244.us-east-1-2.ec2.redns.redis-cloud.com
  _REDIS_PORT: "12651"
  _GOOGLE_API_KEY: AIzaSyA3MM4gaJitv3sv-5CcKIz1QucwY1Nk-4E
  _GCP_LOCATION: us-central1
  _REASONING_MODEL: gemini-1.5-flash-001
  _CHAT_MODEL: gemini-1.5-flash-001
  _VISION_MODEL: gemini-1.5-flash-001
  _EMBEDDING_MODEL: text-embedding-3-small
  _SUPABASE_URL: https://xunzjgmhhirmanvxjedi.supabase.co

options:
  logging: CLOUD_LOGGING_ONLY
  dynamic_substitutions: true

tags:
  - forex-ai
  - cloud-run

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/forex-ai:${SHORT_SHA}' 